### ISSUE TITLE
Windows Module

### ISSUE THREAD

**Issue by DBragz** [DBragz/Ansible#7]
Test the following instructions and add to Windows readme.

1. Install.

  ```shell
  ansible-galaxy collection install community.windows
  ```

2. Verify.

  ```shell
  ansible-galaxy collection list | grep community.windows
  ```

5. Create.

  ```yml
  - name: Get Windows product details
  hosts: windows
  tasks:
    - name: Retrieve product facts
      community.windows.win_product_facts:
    - name: Display Windows edition
      debug:
        var: ansible_os_license_edition  
  ```
